databases:
  - name: melodyflow-redis
    plan: free
    databaseName: melodyflow_db
    ipAllowList: []

services:
  - type: web
    name: melodyflow-api
    region: singapore
    plan: free
    branch: main
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: '10000'
